name: CI Backend

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'server/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/ci-backend.yml'

permissions:
  contents: read

concurrency:
  group: ci-backend
  cancel-in-progress: true

jobs:
  validate-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # First setup without cache so we can generate a lockfile if missing
      - name: Set up Node.js (no cache)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Ensure package-lock.json exists
        run: |
          if [ ! -f package-lock.json ]; then
            npm install --package-lock-only
          fi

      # Re-run setup-node to enable npm cache now that lockfile exists
      - name: Setup npm cache
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint (if present)
        run: npm run lint --if-present

      - name: Server syntax check
        run: node --check server/app.js

      # Placeholder for server tests if/when added
      - name: Run server tests (if present)
        run: npm run test --if-present