name: CI Frontend

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'public/**'
      - 'vite.config.*'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/ci-frontend.yml'

permissions:
  contents: read

concurrency:
  group: ci-frontend
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # First setup without cache so we can generate a lockfile if missing
      - name: Set up Node.js (no cache)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Ensure package-lock.json exists
        run: |
          if [ ! -f package-lock.json ]; then
            npm install --package-lock-only
          fi

      # Re-run setup-node to enable npm cache now that lockfile exists
      - name: Setup npm cache
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # PRs from forks cannot access secrets; use a safe placeholder
      - name: Set backend URL placeholder
        run: echo "VITE_SOCKET_SERVER=" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Lint (if present)
        run: npm run lint --if-present

      - name: Run unit tests (if present)
        env:
          # Ensure jsdom is available for React Testing Library tests if configured
          NODE_ENV: test
        run: npm test --if-present -- --run

      - name: Build frontend
        run: npm run build