name: Deploy to EC2

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy via SSH
              uses: appleboy/ssh-action@v0.1.10
              env:
                  NODE_ENV: ${{ secrets.NODE_ENV }}
                  PORT: ${{ secrets.PORT }}
                  CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
                  EC2_APP_PATH: ${{ secrets.EC2_APP_PATH }}
                  GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
                  GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY }}
                  GOOGLE_SHEETS_SPREADSHEET_ID: ${{ secrets.GOOGLE_SHEETS_SPREADSHEET_ID }}
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ec2-user
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                    echo "🔹 Starting deploy on EC2..."
                    cd ${{ secrets.EC2_APP_PATH }} || exit 1

                    echo "🔹 Ensuring correct permissions..."
                    sudo chown -R ec2-user:ec2-user ${{ secrets.EC2_APP_PATH }}
                    sudo chown -R ec2-user:ec2-user ~/.npm || true

                    # Safely rebuild the .env file
                    rm -f .env
                    cat << 'EOF' > .env
                    NODE_ENV=${{ secrets.NODE_ENV }}
                    PORT=${{ secrets.PORT }}
                    CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}
                    GOOGLE_SERVICE_ACCOUNT_EMAIL=${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
                    GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY=${{ secrets.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY }}
                    GOOGLE_SHEETS_SPREADSHEET_ID=${{ secrets.GOOGLE_SHEETS_SPREADSHEET_ID }}
                    EOF

                    # Adjust permissions
                    chmod 600 .env

                    # Pull and rebuild
                    echo "🔹 Fixing Git safe directory..."
                    git config --global --add safe.directory ${{ secrets.EC2_APP_PATH }}
                    git fetch origin main
                    git reset --hard origin/main
                    echo "🔹 Installing dependencies..."
                    npm ci
                    echo "🔹 Building app..."
                    npm run build

                    echo "🔹 Restarting app with PM2..."
                    pm2 restart ecosystem.config.cjs || pm2 start ecosystem.config.cjs
                    pm2 save

                    echo "✅ Deployment complete!"
